# Form implementation generated from reading ui file 'cod_dialog_clave.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(320, 240)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.txt_clave_previa = QtWidgets.QTextEdit(parent=Dialog)
        self.txt_clave_previa.setReadOnly(True)
        self.txt_clave_previa.setObjectName("txt_clave_previa")
        self.horizontalLayout.addWidget(self.txt_clave_previa)
        self.txt_clave_nueva = QtWidgets.QTextEdit(parent=Dialog)
        self.txt_clave_nueva.setObjectName("txt_clave_nueva")
        self.horizontalLayout.addWidget(self.txt_clave_nueva)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.btn_guardar_clave = QtWidgets.QPushButton(parent=Dialog)
        self.btn_guardar_clave.setObjectName("btn_guardar_clave")
        self.verticalLayout.addWidget(self.btn_guardar_clave)
        self.verticalLayout_2.addLayout(self.verticalLayout)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.txt_clave_previa.setPlaceholderText(_translate("Dialog", "Clave antigua"))
        self.txt_clave_nueva.setPlaceholderText(_translate("Dialog", "Nueva clave"))
        self.btn_guardar_clave.setText(_translate("Dialog", "Guardar clave"))
