# Form implementation generated from reading ui file 'codificador.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(589, 343)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.txt_mensaje = QtWidgets.QTextEdit(parent=self.centralwidget)
        self.txt_mensaje.setObjectName("txt_mensaje")
        self.verticalLayout_2.addWidget(self.txt_mensaje)
        self.txt_codificado = QtWidgets.QTextEdit(parent=self.centralwidget)
        self.txt_codificado.setReadOnly(True)
        self.txt_codificado.setObjectName("txt_codificado")
        self.verticalLayout_2.addWidget(self.txt_codificado)
        self.btn_code = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btn_code.setObjectName("btn_code")
        self.verticalLayout_2.addWidget(self.btn_code)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.txt_codigo = QtWidgets.QTextEdit(parent=self.centralwidget)
        self.txt_codigo.setObjectName("txt_codigo")
        self.verticalLayout.addWidget(self.txt_codigo)
        self.txt_descifrado = QtWidgets.QTextEdit(parent=self.centralwidget)
        self.txt_descifrado.setReadOnly(True)
        self.txt_descifrado.setObjectName("txt_descifrado")
        self.verticalLayout.addWidget(self.txt_descifrado)
        self.btn_decode = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btn_decode.setObjectName("btn_decode")
        self.verticalLayout.addWidget(self.btn_decode)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.gridLayout_2.addLayout(self.horizontalLayout, 1, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 589, 22))
        self.menubar.setObjectName("menubar")
        self.menuCodificacion = QtWidgets.QMenu(parent=self.menubar)
        self.menuCodificacion.setObjectName("menuCodificacion")
        self.menuPasos = QtWidgets.QMenu(parent=self.menubar)
        self.menuPasos.setObjectName("menuPasos")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionCambiar_clave = QtGui.QAction(parent=MainWindow)
        self.actionCambiar_clave.setObjectName("actionCambiar_clave")
        self.actionCambiar_alfabeto = QtGui.QAction(parent=MainWindow)
        self.actionCambiar_alfabeto.setObjectName("actionCambiar_alfabeto")
        self.actionVer = QtGui.QAction(parent=MainWindow)
        self.actionVer.setObjectName("actionVer")
        self.menuCodificacion.addAction(self.actionCambiar_clave)
        self.menuCodificacion.addAction(self.actionCambiar_alfabeto)
        self.menuPasos.addAction(self.actionVer)
        self.menubar.addAction(self.menuCodificacion.menuAction())
        self.menubar.addAction(self.menuPasos.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.txt_mensaje.setPlaceholderText(_translate("MainWindow", "Mensaje original"))
        self.txt_codificado.setPlaceholderText(_translate("MainWindow", "Mensaje codificado"))
        self.btn_code.setText(_translate("MainWindow", "Codificar"))
        self.txt_codigo.setPlaceholderText(_translate("MainWindow", "Mensaje codificado"))
        self.txt_descifrado.setPlaceholderText(_translate("MainWindow", "Mensaje decifrado"))
        self.btn_decode.setText(_translate("MainWindow", "Decodificar"))
        self.menuCodificacion.setTitle(_translate("MainWindow", "Codificacion"))
        self.menuPasos.setTitle(_translate("MainWindow", "Pasos"))
        self.actionCambiar_clave.setText(_translate("MainWindow", "Cambiar clave"))
        self.actionCambiar_alfabeto.setText(_translate("MainWindow", "Cambiar alfabeto"))
        self.actionVer.setText(_translate("MainWindow", "Ver"))
