# Form implementation generated from reading ui file '.\entre_matrices.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(295, 410)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setSizeConstraint(QtWidgets.QLayout.SizeConstraint.SetMaximumSize)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.txt_matriz1 = QtWidgets.QTextEdit(parent=self.centralwidget)
        self.txt_matriz1.setTabChangesFocus(True)
        self.txt_matriz1.setPlaceholderText("")
        self.txt_matriz1.setObjectName("txt_matriz1")
        self.horizontalLayout_2.addWidget(self.txt_matriz1)
        self.txt_matriz2 = QtWidgets.QTextEdit(parent=self.centralwidget)
        self.txt_matriz2.setTabChangesFocus(True)
        self.txt_matriz2.setObjectName("txt_matriz2")
        self.horizontalLayout_2.addWidget(self.txt_matriz2)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.txt_resultado = QtWidgets.QTextEdit(parent=self.centralwidget)
        self.txt_resultado.setEnabled(True)
        self.txt_resultado.setReadOnly(True)
        self.txt_resultado.setObjectName("txt_resultado")
        self.verticalLayout.addWidget(self.txt_resultado)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.btn_suma = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btn_suma.setObjectName("btn_suma")
        self.gridLayout.addWidget(self.btn_suma, 0, 0, 1, 1)
        self.btn_resta = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btn_resta.setObjectName("btn_resta")
        self.gridLayout.addWidget(self.btn_resta, 0, 1, 1, 1)
        self.btn_multiplicacion = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btn_multiplicacion.setObjectName("btn_multiplicacion")
        self.gridLayout.addWidget(self.btn_multiplicacion, 1, 0, 1, 1)
        self.btn_division = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btn_division.setObjectName("btn_division")
        self.gridLayout.addWidget(self.btn_division, 1, 1, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 295, 22))
        self.menubar.setObjectName("menubar")
        self.menuPasos = QtWidgets.QMenu(parent=self.menubar)
        self.menuPasos.setObjectName("menuPasos")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionVer = QtGui.QAction(parent=MainWindow)
        self.actionVer.setObjectName("actionVer")
        self.menuPasos.addAction(self.actionVer)
        self.menubar.addAction(self.menuPasos.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.btn_suma.setText(_translate("MainWindow", "Suma"))
        self.btn_resta.setText(_translate("MainWindow", "Resta"))
        self.btn_multiplicacion.setText(_translate("MainWindow", "Multiplicacion"))
        self.btn_division.setText(_translate("MainWindow", "Division"))
        self.menuPasos.setTitle(_translate("MainWindow", "Pasos"))
        self.actionVer.setText(_translate("MainWindow", "Ver"))
