# Form implementation generated from reading ui file 'operaciones_matriz.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(306, 493)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.txt_matrix1 = QtWidgets.QTextEdit(parent=self.centralwidget)
        self.txt_matrix1.setObjectName("txt_matrix1")
        self.verticalLayout.addWidget(self.txt_matrix1)
        self.btn_inversa = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btn_inversa.setObjectName("btn_inversa")
        self.verticalLayout.addWidget(self.btn_inversa)
        self.btn_determinante = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btn_determinante.setObjectName("btn_determinante")
        self.verticalLayout.addWidget(self.btn_determinante)
        self.btn_rango = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btn_rango.setObjectName("btn_rango")
        self.verticalLayout.addWidget(self.btn_rango)
        self.txt_matrix2 = QtWidgets.QTextEdit(parent=self.centralwidget)
        self.txt_matrix2.setReadOnly(True)
        self.txt_matrix2.setObjectName("txt_matrix2")
        self.verticalLayout.addWidget(self.txt_matrix2)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 306, 22))
        self.menubar.setObjectName("menubar")
        self.menuPasos = QtWidgets.QMenu(parent=self.menubar)
        self.menuPasos.setObjectName("menuPasos")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionVer = QtGui.QAction(parent=MainWindow)
        self.actionVer.setObjectName("actionVer")
        self.menuPasos.addAction(self.actionVer)
        self.menubar.addAction(self.menuPasos.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.btn_inversa.setText(_translate("MainWindow", "Inversa"))
        self.btn_determinante.setText(_translate("MainWindow", "Determinante"))
        self.btn_rango.setText(_translate("MainWindow", "Rango"))
        self.menuPasos.setTitle(_translate("MainWindow", "Pasos"))
        self.actionVer.setText(_translate("MainWindow", "Ver"))
